### ISSUE TITLE
Scrollbar in nav on Windows

### ISSUE THREAD

**Issue by mattwelson** [ryanwiemer/gatsby-theme-amsterdam#1]
There's a scrollbar on the nav which looks a bit funky. Visible on any windows browser. This is due to `overflow-y: scroll`, 

![image](https://user-images.githubusercontent.com/3399530/62087510-12c1e600-b2b6-11e9-9023-071a6fa156f3.png)

Appears on both the variants of the header

**Comment by ryanwiemer** [comment]
Thank you @mattwelson for creating this issue! I'll take a look at this.

**Comment by ryanwiemer** [comment]
This should be resolved in [`v0.0.9`](https://github.com/ryanwiemer/gatsby-theme-amsterdam/releases/tag/v0.0.9). 

As a side note unfortunately I don't have access to a computer with Windows on it. So if you still notice any other weird behavior feel free to log a ticket. It's a big help. 😊
