### ISSUE TITLE
First line of code highlighting block indents

### ISSUE THREAD

**Issue by bravo-kernel** [ryanwiemer/gatsby-theme-amsterdam#4]
Seen in Chrome and Firefox: the first line of code highlighting blocks indents (with and without language specifier).

![image](https://user-images.githubusercontent.com/230500/62785176-66a3aa80-bac0-11e9-8073-3b66c49a1565.png)

**Comment by ryanwiemer** [comment]
Good catch. This will be fixed in the next release.

**Comment by ryanwiemer** [comment]
Fixed in [`v0.0.15`](https://github.com/ryanwiemer/gatsby-theme-amsterdam/releases/tag/v0.0.15)
