### ISSUE TITLE
Replace prism with gatsby-remark-vscode

### ISSUE THREAD

**Issue by bravo-kernel** [ryanwiemer/gatsby-theme-amsterdam#6]
Are you open to replacing prism with https://github.com/andrewbranch/gatsby-remark-vscode?

There is a very good explanation of the benefits on top of their readme page.

As a side question, do you intend to actively develop/maintain this theme or did you just put it up as an entry for the theme-jam? I can imagine both options are possible.

**Comment by bravo-kernel** [comment]
This would obviously make #4 obsolete as well

**Comment by ryanwiemer** [comment]
Thanks for opening up the issue. I think at the moment prism serves me well enough but I will keep this in mind. 

As for the side question I created this theme specifically for the theme-jam but if there is enough interest I would like to maintain it.

**Comment by bravo-kernel** [comment]
Fair enough

**Comment by ryanwiemer** [comment]
Closing this ticket for now but I will take it under consideration
