### ISSUE TITLE
external cover img

### ISSUE THREAD

**Issue by mamged** [ryanwiemer/gatsby-theme-amsterdam#9]
I have an external cdn server hosting my media, when I add the img url instead of local img name it doesn't get it

**Comment by ryanwiemer** [comment]
Sorry for missing this issue a few months back. I will adjust the default cover photo to allow for external urls as well.

Thanks for reporting this!

**Comment by ryanwiemer** [comment]
@mAmged this is now resolved in [`v1.0.0`](https://github.com/ryanwiemer/gatsby-theme-amsterdam/releases/tag/v1.0.0). 

The default SEO image is set in `gatsby-config.js` using  the `siteMetadata`. The full image URL path is required. Please reference the [additional configuration](https://github.com/ryanwiemer/gatsby-theme-amsterdam#additional-configuration) section of the README. 

If you have any questions please let me know.
